apiVersion: v2
name: claude-web-k8s-user
description: Helm chart for per-user namespace infrastructure (RBAC) for Claude Web Kubernetes Engine
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - claude
  - kubernetes
  - multi-tenant
  - rbac
maintainers:
  - name: robotinfra
    email: infra@robotinfra.com
home: https://github.com/robotinfra/claude-web-k8s-user
sources:
  - https://github.com/robotinfra/claude-web-k8s-user
